### PR TITLE
Partial board

### PR DESCRIPTION
**Pull request by isvpursuit**
As far as I can tell, Board seems to be working, but the game is still throwing the 'Cannot complete the action' error when you try to place a ship. Added some tests to Board to make sure everything is working as expected, seems to be working, so I'm not sure what the issue there is.

Looking through game.js to make sure I understand what is being passed through and how the ships are being found, I think the problem is that the game.js isn't finding the stored ships and I'm not 100% positive how it's supposed to be doing this.

### CODE REVIEW

**Comment by leboldh** [comment]
That's really bizarre. I'm looking through the board code and looks like it should work just fine. When you run the game, are you running with the most current version of all classes? I'll try running it too and see if I get the same issue. We might need to talk to a TA or Caius about an issue like this.

**Comment by isvpursuit** [comment]
Yeah, I pulled all the latest files from master last night, so it should all be up to date. Like I said, I'm pretty sure it's just not communicating with game.js properly for some reason. I actually don't really understand how game.js tries to read ships.

**Comment by leboldh** [comment]
I'm getting the same issue when I test the front end. I did try running your tests, too, and I'm getting a ton of errors that BoardTest can't find the Board or Ship classes. Is this happening on your end too?

**Comment by isvpursuit** [comment]
No, the tests were working fine for me. Not sure whats happening on your end.

**Comment by leboldh** [comment]
It must just be something I've got configured funky. It looks like we missed Manideepa's office hours for today, but maybe we can sort this out with Ke-Jo (2-3pm Kelley Atrium) or Caius (3-4pm Kelley Atrium) tomorrow in either of their office hours. Is anybody else available then? I'm not in class from 2-4 so I could stop by, but I also don't have working tests for some reason (files look identical, idk), and I'm not very familiar with what you have going on in the Board class (which I'm assuming the communication between the JS file and board is the problem here).

**Comment by isvpursuit** [comment]
I could do either of those.

**Comment by isvpursuit** [comment]
Whoops, just realized I forgot to implement Attack results for Sunk or Surrender, I'll add that in real fast. Shouldn't change the fact that the board isn't showing up.

**Pull request closed without merging**
