### PR TITLE
Result class

### PR DESCRIPTION
**Pull request by willijo8**

### CODE REVIEW

**Comment by isvpursuit** [comment]
Looks like this is just adding comments to the Result class, should be fine to implement.

**Comment by willijo8** [comment]
I also wrote an initialization for Results so that when it is instantiated, you have to give it the status and the int and char coordinates

**Comment by isvpursuit** [comment]
Ah yeah, my bad. Could you split that into two constructors, one for handling the int and char one for handling the status? No result uses both in the current setup.

**Comment by willijo8** [comment]
Can do, will edit tonight

**Pull request closed without merging**
