### PR TITLE
Willijo8 result-1

### PR DESCRIPTION
**Pull request by willijo8**

### CODE REVIEW

**Comment by willijo8** [comment]
Can someone tell me why my checks keep failing? I genuinely have no idea.

**Comment by leboldh** [comment]
Hey Jonathan sorry for the delay. I'm looking through your code now to see if I can spot why it's not building. Does it build on your computer? Is it just when you upload that the build fails?

**Comment by willijo8** [comment]
The build fails saying that project-haley_jonathan_mark_trevor/target/classes does not exist

**Comment by leboldh** [comment]
So, here's all the issues I found with Result:

I'm getting an error on Line 15 rather than the classes not existing. "this.location = new Square( int x, char y);" seems to be what's causing the build to fail. I think it's because this isn't the right way to declare a new object. Usually when you want a new object you have to say something like "Square sq = new Square(int x, char y);"

Because location already exists, you need to use setColumn and setRow instead. Additionally, adding the data types before x and y is probably confusing Java. I changed line 15 to be "this.location.setColumn(y);" and added "this.location.setRow(x);".

It also needs a default constructor.

**Comment by leboldh** [comment]
In Ship I don't think it likes that you have return statements in the switch statement, because then it can't get to the breaks after the return. The error i'm getting there is "unreachable statement", so I think if you really want the set to return a boolean you'd need to set a boolean to true or false within the switch, and then return it at the end outside of the switch.

**Pull request closed without merging**
